package Source;

import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sofiane
 */
public class GestionProduit extends javax.swing.JFrame {
DefaultTableModel modele;
java.applet.AudioClip son1, son2;

java.net.URL url1 = GestionProduit.class.getResource("/sons/710.wav");
java.net.URL url2 = GestionProduit.class.getResource("/sons/721.wav");
    /**
     * Creates new form GestionProduit
     */
    public GestionProduit() {
        initComponents();
        modele = (DefaultTableModel) jtable_produit.getModel();
        son1 = java.applet.Applet.newAudioClip(url1);
        son2 = java.applet.Applet.newAudioClip(url2);
        jb_son1.setVisible(false);
        jb_son2.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jp_carcac = new javax.swing.JPanel();
        jl_libellé = new javax.swing.JLabel();
        jl_categorie = new javax.swing.JLabel();
        jl_prix = new javax.swing.JLabel();
        jt_libellé = new javax.swing.JTextField();
        jt_prix = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jb_ajouter = new javax.swing.JButton();
        jb_modifier = new javax.swing.JButton();
        jb_supprimer = new javax.swing.JButton();
        jl_warning = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable_produit = new javax.swing.JTable();
        jb_son1 = new javax.swing.JButton();
        jb_son2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Produit");

        jp_carcac.setBorder(javax.swing.BorderFactory.createTitledBorder("Caractéristiques produit"));

        jl_libellé.setText("Libellé");

        jl_categorie.setText("Catégorie");

        jl_prix.setText("Prix Unitaire");

        jt_libellé.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_libelléActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Appareil Photo", "Casque Audio", "Clavier", "Disque Dur Externe", "Lecteur Audio", "Souris", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jb_ajouter.setText("Ajouter");
        jb_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ajouterActionPerformed(evt);
            }
        });

        jb_modifier.setText("Modifier");
        jb_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modifierActionPerformed(evt);
            }
        });

        jb_supprimer.setText("Supprimer");
        jb_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_supprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_carcacLayout = new javax.swing.GroupLayout(jp_carcac);
        jp_carcac.setLayout(jp_carcacLayout);
        jp_carcacLayout.setHorizontalGroup(
            jp_carcacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_carcacLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jp_carcacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_libellé)
                    .addComponent(jl_prix)
                    .addComponent(jl_categorie))
                .addGap(56, 56, 56)
                .addGroup(jp_carcacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_carcacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jt_libellé, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                        .addComponent(jt_prix)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jp_carcacLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_ajouter)
                .addGap(56, 56, 56)
                .addComponent(jb_modifier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_supprimer)
                .addGap(53, 53, 53))
        );
        jp_carcacLayout.setVerticalGroup(
            jp_carcacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_carcacLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_carcacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_libellé)
                    .addComponent(jt_libellé, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jp_carcacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_categorie)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jp_carcacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_prix)
                    .addComponent(jt_prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_carcacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_ajouter)
                    .addComponent(jb_modifier)
                    .addComponent(jb_supprimer))
                .addGap(8, 8, 8))
        );

        jl_warning.setBackground(new java.awt.Color(255, 51, 51));
        jl_warning.setForeground(new java.awt.Color(204, 0, 0));

        jtable_produit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Libellé", "Catégorie", "Prix"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtable_produit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_produitMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtable_produit);

        jb_son1.setText("Test son 1");
        jb_son1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_son1ActionPerformed(evt);
            }
        });

        jb_son2.setText("Test son 2");
        jb_son2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_son2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jp_carcac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jl_warning))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jb_son1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(jb_son2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_carcac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jl_warning)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_son1)
                    .addComponent(jb_son2))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_libelléActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_libelléActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_libelléActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jb_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ajouterActionPerformed

jl_warning.setText("");

Object[] os=new Object[3];
String lib=(String)jt_libellé.getText();
String cate=(String)jComboBox1.getSelectedItem();
Float prix;
if(jt_prix.getText().equals("")) prix=0.f;
else
 prix=Float.parseFloat(jt_prix.getText());

boolean presence=false;

int row=modele.getRowCount();

int i=0;
while ((i<row) && !(presence))
{
    if (modele.getValueAt(i, 0).equals(lib)&&(modele.getValueAt(i, 1).equals(cate)) &&(modele.getValueAt(i, 2).equals(prix))) presence=true;
    i++;
}


if (lib.equals(""))
{
    jl_warning.setText(jl_libellé.getText().trim() +" non specifié");
}
else if (presence) jl_warning.setText("Produit deja éxistant");
else
{
os[0]=lib;
os[1]=cate;
os[2]=prix;
modele.addRow(os);
jb_son1.setVisible(true);
jb_son2.setVisible(true);
}
    }//GEN-LAST:event_jb_ajouterActionPerformed

    private void jb_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modifierActionPerformed
jb_son1.setVisible(false);
jb_son2.setVisible(false);
        
jl_warning.setText("");

int row=jtable_produit.getSelectedRow();

String lib=(String)jt_libellé.getText();
String cate=(String)jComboBox1.getSelectedItem();
Float prix;
if(jt_prix.getText().equals("")) prix=0.f;
else
 prix=Float.parseFloat(jt_prix.getText());

if (lib.equals(""))
{
    jl_warning.setText(jl_libellé.getText().trim() +" non specifié");
}
else if (row==-1) jl_warning.setText("Aucune ligne selectionné");
else
{
modele.setValueAt(lib, row, 0);
modele.setValueAt(cate, row, 1);
modele.setValueAt(prix, row, 2);
}


    }//GEN-LAST:event_jb_modifierActionPerformed

    private void jtable_produitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_produitMouseClicked
       int row=jtable_produit.getSelectedRow();
       String libellé=modele.getValueAt(row, 0).toString();
       String cate=modele.getValueAt(row, 1).toString();
       String prix=modele.getValueAt(row, 2).toString();
       
       jt_libellé.setText(libellé);
       jComboBox1.setSelectedItem(cate);
       jt_prix.setText(prix);
      
       
    }//GEN-LAST:event_jtable_produitMouseClicked

    private void jb_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_supprimerActionPerformed
jb_son1.setVisible(false);
jb_son2.setVisible(false);
jl_warning.setText("");
int row=jtable_produit.getSelectedRow();
modele.removeRow(row);
    }//GEN-LAST:event_jb_supprimerActionPerformed

    private void jb_son1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_son1ActionPerformed
son1.play();        // TODO add your handling code here:
    }//GEN-LAST:event_jb_son1ActionPerformed

    private void jb_son2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_son2ActionPerformed
son2.play();        // TODO add your handling code here:
    }//GEN-LAST:event_jb_son2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionProduit().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_ajouter;
    private javax.swing.JButton jb_modifier;
    private javax.swing.JButton jb_son1;
    private javax.swing.JButton jb_son2;
    private javax.swing.JButton jb_supprimer;
    private javax.swing.JLabel jl_categorie;
    private javax.swing.JLabel jl_libellé;
    private javax.swing.JLabel jl_prix;
    private javax.swing.JLabel jl_warning;
    private javax.swing.JPanel jp_carcac;
    private javax.swing.JTextField jt_libellé;
    private javax.swing.JTextField jt_prix;
    private javax.swing.JTable jtable_produit;
    // End of variables declaration//GEN-END:variables
}
